basePath: /
host: localhost:8080
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: Golang GoFiber swagger auto generate step by step by swaggo
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: GoFiber Example API
  version: "1.0"
paths:
  /api/v1/restaurant:
    get:
      consumes:
      - application/json
      description: Get list of restaurant
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get list of restaurant
      tags:
      - restaurants
swagger: "2.0"
